color: orange
description: null
fieldLayouts:
  4c3ca3f6-4084-4437-98cd-aacdd6d81ee0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-27T21:41:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3fa964ba-0cf2-4961-bdba-d13745fd42f6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-27T21:42:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d911a2a-162d-4f6f-ade3-7e274512eb58 # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c39e40a-7de5-456c-aa82-0df4d5c3a934
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-27T21:42:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: eb780d86-d1b4-4d24-8d74-343c135ef960 # Long Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b3f2809-9abd-459c-a225-cb179cfeeced
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b5e30702-879d-4912-aee8-592b2928ee9f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-19T22:17:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 05b1884e-af00-4d35-bff4-b294519ad2bd # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee680597-d97b-40d1-8a58-40c0f00e95a5
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: e1544869-3427-4aa1-b9f1-367d7b4b0a76
        userCondition: null
handle: pageText
hasTitleField: true
icon: file
name: 'Page - Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
